# Telegram bot and chat settings
[telegram]
api_id = "YOURID"
api_hash = "YOURHASH"

    [telegram.bot]
    token = "YOURTOKEN"
    id = "BOTID"

    [telegram.chat]
    id = "CHATID" 
    language = "en"
    admin_id = "ADMIN_USER_ID"
    admin_phone = "ADMIN_PHONE"

[translation]
# translation support via DeepL
deepl_auth_key = "DEEPL_AUTH_KEY"
#formality level, if supported by the target language. possible values are "less" or "more". set value to "" to use default formality
formality = "less"

# Account info for testing (telegram API is registered in this account)
[testing]

    [testing.account]
    phone = "ADMIN_PHONE"
    user_id = "ADMIN_USER_ID"
    user = "@ADMIN_NICK_NAME"

    [testing.account2]
    user_id = "NONADMIN_USER_ID"
    user = "@NONADMIN_NICK_NAME"